name: tests-authen

on:
  pull_request:
    paths:
      'authen/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd authen && npm install && npm run test:ci
